language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install pytest-cov flake8 codecov"
cache: pip
script:
 - flake8 KartRider tests.py
 - pytest tests.py --cov=KartRider
after_success:
 - codedov